spring.application.name=doyen-control-center
spring.datasource.url=jdbc:postgresql://localhost:5432/hrms
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
springdoc.api-docs.path=/api/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

